version: '3'

services:
  devopsdb:
    restart: always
    image: dev_ops_postgres
    build: ./dev_ops_postgres
    environment:
      - DB_GITLAB_USER=gitlab
      - DB_GITLAB_PASS=gitlab
      - DB_GITLAB_NAME=gitlab
      - DB_TEAMCITY_USER=teamcity
      - DB_TEAMCITY_PASS=teamcity
      - DB_TEAMCITY_NAME=teamcity
    ports:
      - "5432:5432"
    volumes:
      - ./database/data/:/var/lib/postgresql:rw
    networks:
      - 'devops'
  teamcityserver:
    image: jetbrains/teamcity-server
    container_name: devopsteamcityserver
    volumes:
      - './teamcity/teamcity_server/data:/data/teamcity_server/datadir'
      - './teamcity/teamcity_server/logs:/data/teamcity/logs'
    networks:
      - "devops"
    ports:
      - "8111:8111"
    depends_on:
      - devopsdb
  teamcityagent:
    image: jetbrains/teamcity-agent
    container_name: devopsteamcityagent
    networks:
      - "devops"
    ports:
      - "9090:9090"
    environment:
      - SERVER_URL=teamcityserver:8111
    depends_on:
      - teamcityserver
  devopsbitbucket:
    image: 'atlassian/bitbucket-server'
    links:
      - teamcityserver:teamcityserver
    ports:
      - "7990:7990"
      - "7999:7999"
    networks:
      - 'devops'
    depends_on:
      - teamcityserver
  
networks:
  devops: