#!/bin/bash
set -e

POSTGRES="psql --username ${POSTGRES_USER}"

echo "Creating database: ${DB_TEAMCITY_NAME}"

$POSTGRES <<EOSQL
CREATE DATABASE ${DB_TEAMCITY_NAME} OWNER ${DB_TEAMCITY_USER};
GRANT ALL PRIVILEGES ON DATABASE ${DB_TEAMCITY_NAME} TO ${DB_TEAMCITY_USER};
EOSQL

echo "Creating database: ${DB_GITLAB_NAME}"

$POSTGRES <<EOSQL
CREATE DATABASE ${DB_GITLAB_NAME} OWNER ${DB_GITLAB_USER};
EOSQL