#!/bin/bash
set -e

POSTGRES="psql --username ${POSTGRES_USER}"

echo "Creating database role: ${DB_TEAMCITY_USER}"

$POSTGRES <<-EOSQL
CREATE USER ${DB_TEAMCITY_USER} WITH CREATEDB PASSWORD '${DB_TEAMCITY_PASS}';
EOSQL

echo "Creating database role: ${DB_GITLAB_USER}"

$POSTGRES <<-EOSQL
CREATE USER ${DB_GITLAB_USER} WITH CREATEDB PASSWORD '${DB_GITLAB_PASS}';
ALTER USER ${DB_GITLAB_USER} WITH SUPERUSER;
EOSQL
